### ISSUE TITLE
Pollution of CPAN with perl6 modules matching perl5 modules ?

### ISSUE THREAD

**Issue by noxxi** [perl6modules/dists-uploaded-to-cpan#1]
Hi,

I'm the maintainer of the Perl5 module IO::Socket::SSL. Both CPAN and cpantesters are confused by the new Perl6 module IO::Socket::SSL, because it uses the same name even though it is a different thing (Perl5 vs. Perl6). It will show the bugs, rating from the Perl5 module for the Perl6 module and will even list the Perl6 module as the "latest release" when looking at the Perl5 module.

It looks like such kind of  problems were already discussed about two years ago, see https://rdstar.wordpress.com/2014/03/09/perl6-and-cpan/.

**Comment by ranguard** [comment]
Hi Steffen,

PAUSE now accepts Perl 6 modules (see instructions in
https://pause.perl.org/pause/authenquery?ACTION=add_uri  )... we just need
to get everywhere else to cope...

E.g. cpants is updated https://github.com/cpants/www-cpants/issues/78 as is
metacpan https://github.com/CPAN-API/cpan-api/pull/427

Please open issues with cpantesters ( or point me at where you are seeing
the error and I'll chase it up with them).

Many thanks

Leo
